// <auto-generated />
using System;
using DataEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataEF.Migrations
{
    [DbContext(typeof(CredenSoftContext))]
    [Migration("20260920040327_AmpliarDetalleAnexoE")]
    partial class AmpliarDetalleAnexoE
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModelsEntidades.Credencial", b =>
                {
                    b.Property<int>("IdCredencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_credencial");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCredencial"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_emision");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    b.HasKey("IdCredencial");

                    b.HasIndex("IdSolicitud");

                    b.ToTable("credenciales", (string)null);
                });

            modelBuilder.Entity("ModelsEntidades.DetalleAnexoC", b =>
                {
                    b.Property<int>("IdDetalleC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_c");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleC"));

                    b.Property<string>("Aeropuerto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("aeropuerto");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("calle");

                    b.Property<string>("CargoFuncion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cargo_funcion");

                    b.Property<bool>("Conductor")
                        .HasColumnType("bit")
                        .HasColumnName("conductor");

                    b.Property<string>("Cp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cp");

                    b.Property<string>("Depto")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("depto");

                    b.Property<string>("DniPasaporte")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("dni_pasaporte");

                    b.Property<string>("EnfermedadesAlergias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("enfermedades_alergias");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("estado_civil");

                    b.Property<string>("FactorRh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("factor_rh");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("GrupoSanguineo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("grupo_sanguineo");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    b.Property<string>("JustifSnaRegionales")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("justif_sna_regionales");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("localidad");

                    b.Property<string>("LugarNacimiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lugar_nacimiento");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("mail");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("Nro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nro");

                    b.Property<string>("NumeroNotaPermiso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("numero_nota_permiso");

                    b.Property<string>("Piso")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("piso");

                    b.Property<bool>("Sector1")
                        .HasColumnType("bit")
                        .HasColumnName("sector_1");

                    b.Property<string>("Sector1Justif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sector_1_justif");

                    b.Property<bool>("Sector2")
                        .HasColumnType("bit")
                        .HasColumnName("sector_2");

                    b.Property<string>("Sector2Justif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sector_2_justif");

                    b.Property<bool>("Sector3")
                        .HasColumnType("bit")
                        .HasColumnName("sector_3");

                    b.Property<string>("Sector3Justif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sector_3_justif");

                    b.Property<bool>("Sector4")
                        .HasColumnType("bit")
                        .HasColumnName("sector_4");

                    b.Property<string>("Sector4Justif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sector_4_justif");

                    b.Property<bool>("Sector5")
                        .HasColumnType("bit")
                        .HasColumnName("sector_5");

                    b.Property<string>("Sector5Justif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sector_5_justif");

                    b.Property<bool>("Sector6")
                        .HasColumnType("bit")
                        .HasColumnName("sector_6");

                    b.Property<string>("Sector6Justif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sector_6_justif");

                    b.Property<bool>("Sector7")
                        .HasColumnType("bit")
                        .HasColumnName("sector_7");

                    b.Property<string>("Sector7Justif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sector_7_justif");

                    b.Property<bool>("Socorrista")
                        .HasColumnType("bit")
                        .HasColumnName("socorrista");

                    b.Property<string>("TelLaboral")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tel_laboral");

                    b.Property<string>("TelParticular")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tel_particular");

                    b.HasKey("IdDetalleC");

                    b.HasIndex("IdSolicitud")
                        .IsUnique();

                    b.ToTable("detalles_anexo_c", (string)null);
                });

            modelBuilder.Entity("ModelsEntidades.DetalleAnexoE", b =>
                {
                    b.Property<int>("IdDetalleE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_e");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleE"));

                    b.Property<string>("DiasAutorizados")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("dias_autorizados");

                    b.Property<string>("HorariosDesde")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("horarios_desde");

                    b.Property<string>("HorariosHasta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("horarios_hasta");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    b.Property<string>("JustificacionSector1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("justificacion_sector_1");

                    b.Property<string>("JustificacionSector2")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("justificacion_sector_2");

                    b.Property<string>("JustificacionSector3")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("justificacion_sector_3");

                    b.Property<string>("JustificacionSector4")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("justificacion_sector_4");

                    b.Property<string>("JustificacionSector5")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("justificacion_sector_5");

                    b.Property<string>("JustificacionSector6")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("justificacion_sector_6");

                    b.Property<string>("JustificacionSector7")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("justificacion_sector_7");

                    b.Property<string>("Resp2ApeNom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("resp2_apenom");

                    b.Property<string>("Resp2Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("resp2_cargo");

                    b.Property<string>("Resp2NroPermiso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("resp2_nro_permiso");

                    b.Property<string>("ResponsableApNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("responsable_ap_nombre");

                    b.Property<string>("ResponsableCargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("responsable_cargo");

                    b.Property<string>("ResponsableNroPermiso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("responsable_nro_permiso");

                    b.Property<bool>("Sector1")
                        .HasColumnType("bit")
                        .HasColumnName("sector_1");

                    b.Property<bool>("Sector2")
                        .HasColumnType("bit")
                        .HasColumnName("sector_2");

                    b.Property<bool>("Sector3")
                        .HasColumnType("bit")
                        .HasColumnName("sector_3");

                    b.Property<bool>("Sector4")
                        .HasColumnType("bit")
                        .HasColumnName("sector_4");

                    b.Property<bool>("Sector5")
                        .HasColumnType("bit")
                        .HasColumnName("sector_5");

                    b.Property<bool>("Sector6")
                        .HasColumnType("bit")
                        .HasColumnName("sector_6");

                    b.Property<bool>("Sector7")
                        .HasColumnType("bit")
                        .HasColumnName("sector_7");

                    b.Property<string>("Sol1ApeNom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("sol1_apenom");

                    b.Property<string>("Sol1Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sol1_cargo");

                    b.Property<string>("Sol1DocNro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sol1_docnro");

                    b.Property<string>("Sol1TipoDoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sol1_tipodoc");

                    b.Property<string>("Sol2ApeNom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("sol2_apenom");

                    b.Property<string>("Sol2Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sol2_cargo");

                    b.Property<string>("Sol2DocNro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sol2_docnro");

                    b.Property<string>("Sol2TipoDoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sol2_tipodoc");

                    b.Property<string>("Sol3ApeNom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("sol3_apenom");

                    b.Property<string>("Sol3Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sol3_cargo");

                    b.Property<string>("Sol3DocNro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sol3_docnro");

                    b.Property<string>("Sol3TipoDoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sol3_tipodoc");

                    b.Property<string>("Sol4ApeNom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("sol4_apenom");

                    b.Property<string>("Sol4Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sol4_cargo");

                    b.Property<string>("Sol4DocNro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sol4_docnro");

                    b.Property<string>("Sol4TipoDoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sol4_tipodoc");

                    b.Property<string>("Sol5ApeNom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("sol5_apenom");

                    b.Property<string>("Sol5Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sol5_cargo");

                    b.Property<string>("Sol5DocNro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sol5_docnro");

                    b.Property<string>("Sol5TipoDoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sol5_tipodoc");

                    b.Property<string>("Tareas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tareas");

                    b.HasKey("IdDetalleE");

                    b.HasIndex("IdSolicitud")
                        .IsUnique();

                    b.ToTable("detalles_anexo_e", (string)null);
                });

            modelBuilder.Entity("ModelsEntidades.DocumentoAdjunto", b =>
                {
                    b.Property<int>("IdAdjunto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_documento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdjunto"));

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ruta_archivo");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("IdAdjunto");

                    b.HasIndex("IdSolicitud");

                    b.ToTable("documentos_adjuntos");
                });

            modelBuilder.Entity("ModelsEntidades.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ModelsEntidades.Solicitud", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_solicitud");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("TipoSolicitud")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_solicitud");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdUsuario");

                    b.ToTable("solicitudes", (string)null);
                });

            modelBuilder.Entity("ModelsEntidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contrasenia");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ModelsEntidades.Credencial", b =>
                {
                    b.HasOne("ModelsEntidades.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("ModelsEntidades.DetalleAnexoC", b =>
                {
                    b.HasOne("ModelsEntidades.Solicitud", "Solicitud")
                        .WithOne("DetalleAnexoC")
                        .HasForeignKey("ModelsEntidades.DetalleAnexoC", "IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("ModelsEntidades.DetalleAnexoE", b =>
                {
                    b.HasOne("ModelsEntidades.Solicitud", "Solicitud")
                        .WithOne("DetalleAnexoE")
                        .HasForeignKey("ModelsEntidades.DetalleAnexoE", "IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("ModelsEntidades.DocumentoAdjunto", b =>
                {
                    b.HasOne("ModelsEntidades.Solicitud", "Solicitud")
                        .WithMany("ArchivosAdjuntos")
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("ModelsEntidades.Solicitud", b =>
                {
                    b.HasOne("ModelsEntidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ModelsEntidades.Usuario", b =>
                {
                    b.HasOne("ModelsEntidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ModelsEntidades.Solicitud", b =>
                {
                    b.Navigation("ArchivosAdjuntos");

                    b.Navigation("DetalleAnexoC")
                        .IsRequired();

                    b.Navigation("DetalleAnexoE")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
