// <auto-generated />
using System;
using DataEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataEF.Migrations
{
    [DbContext(typeof(CredenSoftContext))]
    [Migration("20260907212455_AgregarEstadoASolicitud")]
    partial class AgregarEstadoASolicitud
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModelsEntidades.Credencial", b =>
                {
                    b.Property<int>("IdCredencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_credencial");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCredencial"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_emision");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    b.HasKey("IdCredencial");

                    b.HasIndex("IdSolicitud");

                    b.ToTable("credenciales", (string)null);
                });

            modelBuilder.Entity("ModelsEntidades.DetalleAnexoC", b =>
                {
                    b.Property<int>("IdDetalleC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_c");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleC"));

                    b.Property<string>("Aeropuerto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("aeropuerto");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("calle");

                    b.Property<string>("Cp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cp");

                    b.Property<string>("DatosSocorristaConductor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("datos_socorrista_conductor");

                    b.Property<string>("Depto")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("depto");

                    b.Property<string>("EnfermedadesAlergias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("enfermedades_alergias");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("estado_civil");

                    b.Property<string>("FactorRh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("factor_rh");

                    b.Property<string>("GrupoSanguineo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("grupo_sanguineo");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("localidad");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("mail");

                    b.Property<string>("Nro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nro");

                    b.Property<string>("NumeroNotaPermiso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("numero_nota_permiso");

                    b.Property<string>("Piso")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("piso");

                    b.Property<string>("TelLaboral")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tel_laboral");

                    b.Property<string>("TelParticular")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tel_particular");

                    b.HasKey("IdDetalleC");

                    b.HasIndex("IdSolicitud")
                        .IsUnique();

                    b.ToTable("detalles_anexo_c", (string)null);
                });

            modelBuilder.Entity("ModelsEntidades.DetalleAnexoE", b =>
                {
                    b.Property<int>("IdDetalleE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_e");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleE"));

                    b.Property<string>("DiasAutorizados")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("dias_autorizados");

                    b.Property<string>("HorariosDesde")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("horarios_desde");

                    b.Property<string>("HorariosHasta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("horarios_hasta");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    b.Property<string>("JustificacionSector1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("justificacion_sector_1");

                    b.Property<string>("JustificacionSector2")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("justificacion_sector_2");

                    b.Property<string>("JustificacionSector3")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("justificacion_sector_3");

                    b.Property<string>("JustificacionSector4")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("justificacion_sector_4");

                    b.Property<string>("JustificacionSector5")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("justificacion_sector_5");

                    b.Property<string>("JustificacionSector6")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("justificacion_sector_6");

                    b.Property<string>("JustificacionSector7")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("justificacion_sector_7");

                    b.Property<string>("ResponsableApNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("responsable_ap_nombre");

                    b.Property<string>("ResponsableCargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("responsable_cargo");

                    b.Property<string>("ResponsableNroPermiso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("responsable_nro_permiso");

                    b.Property<bool>("Sector1")
                        .HasColumnType("bit")
                        .HasColumnName("sector_1");

                    b.Property<bool>("Sector2")
                        .HasColumnType("bit")
                        .HasColumnName("sector_2");

                    b.Property<bool>("Sector3")
                        .HasColumnType("bit")
                        .HasColumnName("sector_3");

                    b.Property<bool>("Sector4")
                        .HasColumnType("bit")
                        .HasColumnName("sector_4");

                    b.Property<bool>("Sector5")
                        .HasColumnType("bit")
                        .HasColumnName("sector_5");

                    b.Property<bool>("Sector6")
                        .HasColumnType("bit")
                        .HasColumnName("sector_6");

                    b.Property<bool>("Sector7")
                        .HasColumnType("bit")
                        .HasColumnName("sector_7");

                    b.HasKey("IdDetalleE");

                    b.HasIndex("IdSolicitud")
                        .IsUnique();

                    b.ToTable("detalles_anexo_e", (string)null);
                });

            modelBuilder.Entity("ModelsEntidades.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ModelsEntidades.Solicitud", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_solicitud");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("TipoSolicitud")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_solicitud");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdUsuario");

                    b.ToTable("solicitudes", (string)null);
                });

            modelBuilder.Entity("ModelsEntidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contrasenia");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ModelsEntidades.Credencial", b =>
                {
                    b.HasOne("ModelsEntidades.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("ModelsEntidades.DetalleAnexoC", b =>
                {
                    b.HasOne("ModelsEntidades.Solicitud", "Solicitud")
                        .WithOne("DetalleAnexoC")
                        .HasForeignKey("ModelsEntidades.DetalleAnexoC", "IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("ModelsEntidades.DetalleAnexoE", b =>
                {
                    b.HasOne("ModelsEntidades.Solicitud", "Solicitud")
                        .WithOne("DetalleAnexoE")
                        .HasForeignKey("ModelsEntidades.DetalleAnexoE", "IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("ModelsEntidades.Solicitud", b =>
                {
                    b.HasOne("ModelsEntidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ModelsEntidades.Usuario", b =>
                {
                    b.HasOne("ModelsEntidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ModelsEntidades.Solicitud", b =>
                {
                    b.Navigation("DetalleAnexoC")
                        .IsRequired();

                    b.Navigation("DetalleAnexoE")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
